[package]
name = "asimov-search"
version.workspace = true
edition.workspace = true

[features]
default = []
semantic = []
watch = []

[dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
walkdir = { workspace = true }
glob = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
lz4_flex = "0.11"
syntect = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
